### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Kamm34** [elishacloud/BloodRayne-2-Patch#2] opened 2018-01-09 21:08 UTC
Hi Elisha,

I've obtained a very strange error code using your patch. Since I have no programming skills I'd like to ask you if you could find out what the problem is. I've searched for any other users obtaining this error, but it seems I'm the only one.

With kind regards
Pierre Homrighausen

![screenshot](https://user-images.githubusercontent.com/35275451/34743274-86657b94-f589-11e7-8e23-d061213bf188.png)

**Comment by Kamm34** [comment] 2018-01-09 21:11
Oh, I've forgotten one thing: The error shows off by starting the br2fsaaConfig.exe, not the br2.exe.

**Comment by elishacloud** [comment] 2018-01-11 06:57
@Kamm34, this looks like a language issue with the .NET code.  Unfortunately I did not write that code and I cannot reproduce the issue.  It seems like the program is being told that the language is "DE" but it should be told that the language is "de-DE".  I am guessing you are using a language that the original author did not expect.

I was able to find a similar issue [here](https://steamcommunity.com/app/289130/discussions/0/613937306570494259/?l=german).

There are basically two steps:
1. Make sure that none of the files in your BloodRayne 2 folder are read only.
 a) Right-click on “BloodRayne 2” folder
 b) Select “Properties”
 c) Deselect the Read-only option.

2. Modify the compatibility settings of br2fsaaConfig.exe to "Windows 7"
 a) Locate the br2fsaaConfig.exe executable.
 b) Right click on the exe and select "Properties"
 c) Select the "Compatibility" tab
 d) Check the "Run this program in compatibility for" and select "Windows 7"

**Comment by Kamm34** [comment] 2018-01-11 17:13
@elishacloud 
I've tried the suggestions, but unfortunately with no luck. The error stays the same.
I'll try to contact the original author of the mod.
Anyway, thank you for your help!

**Comment by elishacloud** [comment] 2018-01-11 18:25
You could try the steps [here](https://www.maketecheasier.com/set-individual-app-languages-windows-8/) or [here](https://www.addictivetips.com/windows-tips/how-to-set-language-on-a-per-app-basis-in-windows-10/) to set the language up for this application to use English.  I know it works with English since that is what I use.

Also you can see the original developer's comment to another issue [here](https://steamcommunity.com/app/3820/discussions/0/535152276585406170/#c517141624286794292).

**Comment by Kamm34** [comment] 2018-01-12 19:25
Elishacloud, thank you very much!
It turns out installing the english (United States) language pack for Windows 10 was enough to get the mod to run. All I had to do to play it in 4k was to additionally set the flag 'force simple window' via the Windows Compatibility Administrator.
Thank you again for your fast and competend help!

**Comment by elishacloud** [comment] 2018-01-13 06:15
Very good!  Closing the issue since it is now resolved.

**Closed as completed by elishacloud** 2018-01-13 06:15 UTC
